/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import { ClaimArgs, claimArgsBeet } from '../types/ClaimArgs'

/**
 * @category Instructions
 * @category Claim
 * @category generated
 */
export type ClaimInstructionArgs = {
  args: ClaimArgs
}
/**
 * @category Instructions
 * @category Claim
 * @category generated
 */
export const claimStruct = new beet.FixableBeetArgsStruct<
  ClaimInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['args', claimArgsBeet],
  ],
  'ClaimInstructionArgs'
)
/**
 * Accounts required by the _claim_ instruction
 *
 * @property [_writable_, **signer**] claimant
 * @property [_writable_] claimantTokenAccount
 * @property [_writable_] distributor
 * @property [_writable_] distributorTokenAccount
 * @property [_writable_] claimStatus
 * @property [] mint
 * @property [] associatedTokenProgram
 * @category Instructions
 * @category Claim
 * @category generated
 */
export type ClaimInstructionAccounts = {
  claimant: web3.PublicKey
  claimantTokenAccount: web3.PublicKey
  distributor: web3.PublicKey
  distributorTokenAccount: web3.PublicKey
  claimStatus: web3.PublicKey
  systemProgram?: web3.PublicKey
  tokenProgram?: web3.PublicKey
  mint: web3.PublicKey
  associatedTokenProgram: web3.PublicKey
  rent?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const claimInstructionDiscriminator = [
  62, 198, 214, 193, 213, 159, 108, 210,
]

/**
 * Creates a _Claim_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category Claim
 * @category generated
 */
export function createClaimInstruction(
  accounts: ClaimInstructionAccounts,
  args: ClaimInstructionArgs,
  programId = new web3.PublicKey('AZMc26abaSP7si1wtLaV5yPxTxpWd895M8YpJFFdQ8Qw')
) {
  const [data] = claimStruct.serialize({
    instructionDiscriminator: claimInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.claimant,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.claimantTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.distributor,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.distributorTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.claimStatus,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.mint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.associatedTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
