/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category CloseTokenAccountWithFee
 * @category generated
 */
export const closeTokenAccountWithFeeStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'CloseTokenAccountWithFeeInstructionArgs'
)
/**
 * Accounts required by the _closeTokenAccountWithFee_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [_writable_] signerTokenAccount
 * @property [_writable_] feeCollector
 * @property [] mint
 * @property [] associatedTokenProgram
 * @category Instructions
 * @category CloseTokenAccountWithFee
 * @category generated
 */
export type CloseTokenAccountWithFeeInstructionAccounts = {
  signer: web3.PublicKey
  signerTokenAccount: web3.PublicKey
  feeCollector: web3.PublicKey
  mint: web3.PublicKey
  systemProgram?: web3.PublicKey
  tokenProgram?: web3.PublicKey
  associatedTokenProgram: web3.PublicKey
  rent?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const closeTokenAccountWithFeeInstructionDiscriminator = [
  99, 65, 147, 154, 145, 144, 122, 144,
]

/**
 * Creates a _CloseTokenAccountWithFee_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category CloseTokenAccountWithFee
 * @category generated
 */
export function createCloseTokenAccountWithFeeInstruction(
  accounts: CloseTokenAccountWithFeeInstructionAccounts,
  programId = new web3.PublicKey('AZMc26abaSP7si1wtLaV5yPxTxpWd895M8YpJFFdQ8Qw')
) {
  const [data] = closeTokenAccountWithFeeStruct.serialize({
    instructionDiscriminator: closeTokenAccountWithFeeInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.signerTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.feeCollector,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.mint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.associatedTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
