/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link AirDropper}
 * @category Accounts
 * @category generated
 */
export type AirDropperArgs = {
  bump: number
  owner: web3.PublicKey
}

export const airDropperDiscriminator = [208, 201, 23, 193, 77, 215, 158, 19]
/**
 * Holds the data for the {@link AirDropper} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class AirDropper implements AirDropperArgs {
  private constructor(readonly bump: number, readonly owner: web3.PublicKey) {}

  /**
   * Creates a {@link AirDropper} instance from the provided args.
   */
  static fromArgs(args: AirDropperArgs) {
    return new AirDropper(args.bump, args.owner)
  }

  /**
   * Deserializes the {@link AirDropper} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [AirDropper, number] {
    return AirDropper.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link AirDropper} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<AirDropper> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find AirDropper account at ${address}`)
    }
    return AirDropper.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'AZMc26abaSP7si1wtLaV5yPxTxpWd895M8YpJFFdQ8Qw'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, airDropperBeet)
  }

  /**
   * Deserializes the {@link AirDropper} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [AirDropper, number] {
    return airDropperBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link AirDropper} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return airDropperBeet.serialize({
      accountDiscriminator: airDropperDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link AirDropper}
   */
  static get byteSize() {
    return airDropperBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link AirDropper} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      AirDropper.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link AirDropper} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === AirDropper.byteSize
  }

  /**
   * Returns a readable version of {@link AirDropper} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      bump: this.bump,
      owner: this.owner.toBase58(),
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const airDropperBeet = new beet.BeetStruct<
  AirDropper,
  AirDropperArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['bump', beet.u8],
    ['owner', beetSolana.publicKey],
  ],
  AirDropper.fromArgs,
  'AirDropper'
)
