/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type ClaimArgs = {
  index: beet.bignum
  amount: beet.bignum
  proof: number[] /* size: 32 */[]
}

/**
 * @category userTypes
 * @category generated
 */
export const claimArgsBeet = new beet.FixableBeetArgsStruct<ClaimArgs>(
  [
    ['index', beet.u64],
    ['amount', beet.u64],
    ['proof', beet.array(beet.uniformFixedSizeArray(beet.u8, 32))],
  ],
  'ClaimArgs'
)
