/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type CreateDistributorArgs = {
  root: number[] /* size: 32 */
  maxTotalClaim: beet.bignum
  maxNumNodes: beet.bignum
  leavesLen: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const createDistributorArgsBeet =
  new beet.BeetArgsStruct<CreateDistributorArgs>(
    [
      ['root', beet.uniformFixedSizeArray(beet.u8, 32)],
      ['maxTotalClaim', beet.u64],
      ['maxNumNodes', beet.u64],
      ['leavesLen', beet.u64],
    ],
    'CreateDistributorArgs'
  )
