/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type CreateFeeCollectorArgs = {
  fee: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const createFeeCollectorArgsBeet =
  new beet.BeetArgsStruct<CreateFeeCollectorArgs>(
    [['fee', beet.u64]],
    'CreateFeeCollectorArgs'
  )
