/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  CreateMarkerArgs,
  createMarkerArgsBeet,
} from '../types/CreateMarkerArgs'

/**
 * @category Instructions
 * @category CreateMarker
 * @category generated
 */
export type CreateMarkerInstructionArgs = {
  args: CreateMarkerArgs
}
/**
 * @category Instructions
 * @category CreateMarker
 * @category generated
 */
export const createMarkerStruct = new beet.BeetArgsStruct<
  CreateMarkerInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['args', createMarkerArgsBeet],
  ],
  'CreateMarkerInstructionArgs'
)
/**
 * Accounts required by the _createMarker_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [_writable_] signerTokenAccount
 * @property [] claimant
 * @property [] airDropper
 * @property [_writable_] claimMarker
 * @property [_writable_] claimMarkerTokenAccount
 * @property [] mint
 * @property [] associatedTokenProgram
 * @category Instructions
 * @category CreateMarker
 * @category generated
 */
export type CreateMarkerInstructionAccounts = {
  signer: web3.PublicKey
  signerTokenAccount: web3.PublicKey
  claimant: web3.PublicKey
  airDropper: web3.PublicKey
  claimMarker: web3.PublicKey
  claimMarkerTokenAccount: web3.PublicKey
  mint: web3.PublicKey
  systemProgram?: web3.PublicKey
  tokenProgram?: web3.PublicKey
  associatedTokenProgram: web3.PublicKey
  rent?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const createMarkerInstructionDiscriminator = [
  31, 145, 164, 36, 120, 97, 80, 8,
]

/**
 * Creates a _CreateMarker_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CreateMarker
 * @category generated
 */
export function createCreateMarkerInstruction(
  accounts: CreateMarkerInstructionAccounts,
  args: CreateMarkerInstructionArgs,
  programId = new web3.PublicKey('AZMc26abaSP7si1wtLaV5yPxTxpWd895M8YpJFFdQ8Qw')
) {
  const [data] = createMarkerStruct.serialize({
    instructionDiscriminator: createMarkerInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.signerTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.claimant,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.airDropper,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.claimMarker,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.claimMarkerTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.mint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.associatedTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
