DROP TRIGGER IF EXISTS trg_make_archive_of_changes_for_users_ip ON users_ip;
DROP TRIGGER IF EXISTS trg_make_archive_of_changes_for_ip_addresses ON ip_addresses;
DROP TRIGGER IF EXISTS trg_make_archive_of_changes_for_analytics ON analytics;