#!/bin/sh
set -e
export _PWD="$(pwd)"
export ROOT="$(git rev-parse --show-toplevel)"
source "${ROOT}/scripts/setup.sh"
export CARGO_TARGET_DIR="${ROOT}/target/PRE-PUSH"
current_branch=$(git branch --show-current)
if [ $current_branch == "master" ] ; then
        echo "Cannot commit to master"
        exit 1
fi

echo '+cargo test --all'
cargo test --all
echo '+cargo clippy --all -- -D warnings'
cargo clippy --all -- -D warnings
echo '+cargo fmt --all -- --check'
cargo fmt --all -- --check