name: Release
permissions:
  contents: "write"
on:
  push:
    branches:
      - test-release-workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  upload-assets:
    name: "Upload assets to Github releases"
    strategy:
      matrix:
        include:
          - target: "x86_64-unknown-linux-gnu"
            os: "ubuntu-latest"
          - target: "x86_64-unknown-linux-musl"
            os: "ubuntu-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v4
      - name: "Install deps"
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config openssl libssl-dev
      - name: "Cache"
        uses: Swatinem/rust-cache@v2
        with:
          key: release-upload-${{ matrix.target }}
          cache-all-crates: true
      - name: "Upload Binaries"
        uses: "taiki-e/upload-rust-binary-action@v1"
        with:
          bin: "block-mesh-manager"
          target: ${{ matrix.target }}
          archive: $bin-${{ matrix.target }}
          ref: refs/tags/v${{ needs.get-tag.outputs.pkg-version }}
          token: ${{ secrets.GITHUB_TOKEN }}